In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('qoute_dataset.csv')

In [ ]:
df.shape

(3038, 2)

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
quote=df['quote']

In [ ]:
quote.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
print(type(quote))

<class 'pandas.core.series.Series'>

In [ ]:
quote=quote.str.lower()

In [ ]:
quote[0]

'“the world as we have created it is a process of our thinking. it cannot be changed without changing our thinking.”'

In [ ]:
import string
punc=string.punctuation + '“”‘’'

translator=str.maketrans('','',punc)

In [ ]:
quote=quote.apply(lambda x: x.translate(translator))

In [ ]:
quote.head()

0    the world as we have created it is a process o...
1    it is our choices harry that show what we trul...
2    there are only two ways to live your life one ...
3    the person be it gentleman or lady who has not...
4    imperfection is beauty madness is genius and i...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size=8770

tok=Tokenizer(num_words=vocab_size, oov_token='<OOV>')
tok.fit_on_texts(quote)

In [ ]:
word_index=tok.word_index

In [ ]:
len(word_index)

8770

In [ ]:
list(word_index.items())[:10]

[('<OOV>', 1),
 ('the', 2),
 ('you', 3),
 ('to', 4),
 ('and', 5),
 ('a', 6),
 ('i', 7),
 ('is', 8),
 ('of', 9),
 ('that', 10)]

In [ ]:
sequence=tok.texts_to_sequences(quote)

In [ ]:
sequence[0]

[2,
 63,
 30,
 20,
 17,
 940,
 11,
 8,
 6,
 1144,
 9,
 71,
 286,
 11,
 147,
 13,
 806,
 106,
 744,
 71,
 286]

In [ ]:
X=[]
y=[]

for seq in sequence:
  for i in range(1,len(seq)):
    X.append(seq[:i])
    y.append(seq[i])

In [ ]:
X[:5]

[[2], [2, 63], [2, 63, 30], [2, 63, 30, 20], [2, 63, 30, 20, 17]]

In [ ]:
y[:5]

[63, 30, 20, 17, 940]

In [ ]:
len(X)

85269

In [ ]:
len(y)

85269

In [ ]:
max_len=max(len(x) for x in X)

In [ ]:
max_len

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
X_padded=pad_sequences(X,maxlen=max_len, padding='pre')

In [ ]:
X_padded[:5]

array([[ 0,  0,  0, ...,  0,  0,  2],
       [ 0,  0,  0, ...,  0,  2, 63],
       [ 0,  0,  0, ...,  2, 63, 30],
       [ 0,  0,  0, ..., 63, 30, 20],
       [ 0,  0,  0, ..., 30, 20, 17]], dtype=int32)

In [ ]:
len(X_padded[0])

745

In [ ]:
type(y)

list

In [ ]:
y=np.array(y)

In [ ]:
X_padded.shape

(85269, 745)

In [ ]:
y.shape

(85269,)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Dropout, SimpleRNN, LSTM

In [ ]:
embedding_dim=50
rnn_units=128

In [ ]:
rnn_model=Sequential()
rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units,))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
rnn_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model=Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(
    LSTM(units=rnn_units)
)
lstm_model.add(
    Dense(units=vocab_size,activation='softmax')
)

In [ ]:
lstm_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
lstm_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs=10
batch_size=64

In [ ]:
#rnn_model.fit(X_padded,y,epochs=epochs, batch_size=batch_size, validation_split=0.1)

In [ ]:
lstm_model.save('rnn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
epochs=100
batch_size=64

In [ ]:
lstm_model.fit(X_padded,y,epochs=epochs, batch_size=batch_size, validation_split=0.1)

Epoch 1/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 50s 37ms/step - accuracy: 0.0437 - loss: 6.6694 - val_accuracy: 0.0566 - val_loss: 6.5896
Epoch 2/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.0726 - loss: 6.1435 - val_accuracy: 0.0863 - val_loss: 6.3746
Epoch 3/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.0978 - loss: 5.8123 - val_accuracy: 0.0998 - val_loss: 6.3278
Epoch 4/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.1142 - loss: 5.5401 - val_accuracy: 0.1047 - val_loss: 6.3100
Epoch 5/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.1297 - loss: 5.2908 - val_accuracy: 0.1123 - val_loss: 6.3580
Epoch 6/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.1422 - loss: 5.0624 - val_accuracy: 0.1143 - val_loss: 6.4519
Epoch 7/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 36ms/step - accuracy: 0.1529 - loss: 4.8478 - val_accuracy: 0.1159 - val_loss: 6.4965
Epoch 8/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.1644 - loss: 4.6458 - val_accuracy: 0.1160 - val_loss: 6.5955
Epoch 9/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.1788 - loss: 4.4491 - val_accuracy: 0.1135 - val_loss: 6.6884
Epoch 10/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.1917 - loss: 4.2874 - val_accuracy: 0.1148 - val_loss: 6.7929
Epoch 11/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.2115 - loss: 4.0895 - val_accuracy: 0.1128 - val_loss: 6.9083
Epoch 12/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.2355 - loss: 3.9181 - val_accuracy: 0.1129 - val_loss: 7.0301
Epoch 13/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.2574 - loss: 3.7583 - val_accuracy: 0.1109 - val_loss: 7.1375
Epoch 14/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.2806 - loss: 3.6103 - val_accuracy: 0.1077 - val_loss: 7.2483
Epoch 15/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.3006 - loss: 3.4715 - val_accuracy: 0.1066 - val_loss: 7.3517
Epoch 16/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 36ms/step - accuracy: 0.3218 - loss: 3.3476 - val_accuracy: 0.1073 - val_loss: 7.4637
Epoch 17/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.3412 - loss: 3.2291 - val_accuracy: 0.1027 - val_loss: 7.5621
Epoch 18/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.3578 - loss: 3.1227 - val_accuracy: 0.1053 - val_loss: 7.6353
Epoch 19/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.3761 - loss: 3.0205 - val_accuracy: 0.1046 - val_loss: 7.7423
Epoch 20/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.3914 - loss: 2.9260 - val_accuracy: 0.1053 - val_loss: 7.8358
Epoch 21/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.4059 - loss: 2.8369 - val_accuracy: 0.1017 - val_loss: 7.9035
Epoch 22/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.4226 - loss: 2.7510 - val_accuracy: 0.1018 - val_loss: 8.0139
Epoch 23/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.4364 - loss: 2.6710 - val_accuracy: 0.1010 - val_loss: 8.0988
Epoch 24/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.4503 - loss: 2.5930 - val_accuracy: 0.0984 - val_loss: 8.1771
Epoch 25/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.4634 - loss: 2.5199 - val_accuracy: 0.0987 - val_loss: 8.2710
Epoch 26/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.4767 - loss: 2.4517 - val_accuracy: 0.0997 - val_loss: 8.3569
Epoch 27/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.4889 - loss: 2.3832 - val_accuracy: 0.0968 - val_loss: 8.4506
Epoch 28/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.5007 - loss: 2.3187 - val_accuracy: 0.0956 - val_loss: 8.5281
Epoch 29/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.5139 - loss: 2.2565 - val_accuracy: 0.0962 - val_loss: 8.6067
Epoch 30/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.5250 - loss: 2.1978 - val_accuracy: 0.0943 - val_loss: 8.6937
Epoch 31/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.5360 - loss: 2.1429 - val_accuracy: 0.0915 - val_loss: 8.8083
Epoch 32/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.5461 - loss: 2.0862 - val_accuracy: 0.0912 - val_loss: 8.8522
Epoch 33/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.5566 - loss: 2.0359 - val_accuracy: 0.0901 - val_loss: 8.9656
Epoch 34/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 36ms/step - accuracy: 0.5674 - loss: 1.9860 - val_accuracy: 0.0894 - val_loss: 9.0499
Epoch 35/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.5763 - loss: 1.9379 - val_accuracy: 0.0896 - val_loss: 9.1172
Epoch 36/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.5853 - loss: 1.8917 - val_accuracy: 0.0861 - val_loss: 9.1916
Epoch 37/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.5948 - loss: 1.8460 - val_accuracy: 0.0881 - val_loss: 9.2913
Epoch 38/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6030 - loss: 1.8043 - val_accuracy: 0.0890 - val_loss: 9.3706
Epoch 39/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.6125 - loss: 1.7622 - val_accuracy: 0.0855 - val_loss: 9.4487
Epoch 40/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6199 - loss: 1.7234 - val_accuracy: 0.0853 - val_loss: 9.5219
Epoch 41/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.6287 - loss: 1.6838 - val_accuracy: 0.0849 - val_loss: 9.5943
Epoch 42/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6355 - loss: 1.6476 - val_accuracy: 0.0848 - val_loss: 9.6770
Epoch 43/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.6437 - loss: 1.6133 - val_accuracy: 0.0853 - val_loss: 9.7667
Epoch 44/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6517 - loss: 1.5779 - val_accuracy: 0.0835 - val_loss: 9.8481
Epoch 45/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.6589 - loss: 1.5446 - val_accuracy: 0.0849 - val_loss: 9.9526
Epoch 46/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 37ms/step - accuracy: 0.6636 - loss: 1.5131 - val_accuracy: 0.0805 - val_loss: 9.9989
Epoch 47/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6704 - loss: 1.4818 - val_accuracy: 0.0844 - val_loss: 10.1043
Epoch 48/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.6770 - loss: 1.4536 - val_accuracy: 0.0799 - val_loss: 10.1721
Epoch 49/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6834 - loss: 1.4230 - val_accuracy: 0.0793 - val_loss: 10.2673
Epoch 50/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.6899 - loss: 1.3959 - val_accuracy: 0.0789 - val_loss: 10.3252
Epoch 51/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.6948 - loss: 1.3702 - val_accuracy: 0.0792 - val_loss: 10.4003
Epoch 52/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7011 - loss: 1.3430 - val_accuracy: 0.0806 - val_loss: 10.4677
Epoch 53/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 36ms/step - accuracy: 0.7067 - loss: 1.3175 - val_accuracy: 0.0768 - val_loss: 10.5543
Epoch 54/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.7120 - loss: 1.2940 - val_accuracy: 0.0799 - val_loss: 10.6592
Epoch 55/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.7166 - loss: 1.2697 - val_accuracy: 0.0781 - val_loss: 10.7153
Epoch 56/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.7229 - loss: 1.2489 - val_accuracy: 0.0780 - val_loss: 10.7760
Epoch 57/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.7265 - loss: 1.2251 - val_accuracy: 0.0785 - val_loss: 10.8710
Epoch 58/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.7325 - loss: 1.2017 - val_accuracy: 0.0741 - val_loss: 10.9343
Epoch 59/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.7344 - loss: 1.1865 - val_accuracy: 0.0746 - val_loss: 11.0366
Epoch 60/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.7389 - loss: 1.1619 - val_accuracy: 0.0751 - val_loss: 11.0924
Epoch 61/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7441 - loss: 1.1423 - val_accuracy: 0.0781 - val_loss: 11.1450
Epoch 62/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.7488 - loss: 1.1255 - val_accuracy: 0.0774 - val_loss: 11.2415
Epoch 63/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.7513 - loss: 1.1063 - val_accuracy: 0.0767 - val_loss: 11.3105
Epoch 64/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 37ms/step - accuracy: 0.7562 - loss: 1.0873 - val_accuracy: 0.0768 - val_loss: 11.3748
Epoch 65/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.7593 - loss: 1.0706 - val_accuracy: 0.0768 - val_loss: 11.4077
Epoch 66/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7632 - loss: 1.0552 - val_accuracy: 0.0751 - val_loss: 11.5132
Epoch 67/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.7672 - loss: 1.0381 - val_accuracy: 0.0747 - val_loss: 11.5594
Epoch 68/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7705 - loss: 1.0215 - val_accuracy: 0.0768 - val_loss: 11.6456
Epoch 69/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.7731 - loss: 1.0053 - val_accuracy: 0.0762 - val_loss: 11.6973
Epoch 70/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 45s 37ms/step - accuracy: 0.7783 - loss: 0.9882 - val_accuracy: 0.0728 - val_loss: 11.7621
Epoch 71/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7817 - loss: 0.9758 - val_accuracy: 0.0767 - val_loss: 11.8762
Epoch 72/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 45s 37ms/step - accuracy: 0.7840 - loss: 0.9617 - val_accuracy: 0.0726 - val_loss: 11.9108
Epoch 73/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7849 - loss: 0.9520 - val_accuracy: 0.0751 - val_loss: 11.9775
Epoch 74/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 45s 37ms/step - accuracy: 0.7904 - loss: 0.9342 - val_accuracy: 0.0739 - val_loss: 11.9998
Epoch 75/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7924 - loss: 0.9223 - val_accuracy: 0.0713 - val_loss: 12.1019
Epoch 76/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7953 - loss: 0.9096 - val_accuracy: 0.0726 - val_loss: 12.1300
Epoch 77/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.7964 - loss: 0.9038 - val_accuracy: 0.0760 - val_loss: 12.2144
Epoch 78/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8015 - loss: 0.8845 - val_accuracy: 0.0733 - val_loss: 12.2507
Epoch 79/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8045 - loss: 0.8709 - val_accuracy: 0.0731 - val_loss: 12.3515
Epoch 80/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8051 - loss: 0.8613 - val_accuracy: 0.0715 - val_loss: 12.4103
Epoch 81/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8090 - loss: 0.8501 - val_accuracy: 0.0725 - val_loss: 12.4516
Epoch 82/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8114 - loss: 0.8363 - val_accuracy: 0.0728 - val_loss: 12.5248
Epoch 83/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 37ms/step - accuracy: 0.8133 - loss: 0.8269 - val_accuracy: 0.0725 - val_loss: 12.5609
Epoch 84/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 45s 37ms/step - accuracy: 0.8124 - loss: 0.8219 - val_accuracy: 0.0715 - val_loss: 12.6615
Epoch 85/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8185 - loss: 0.8036 - val_accuracy: 0.0736 - val_loss: 12.7037
Epoch 86/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8189 - loss: 0.7971 - val_accuracy: 0.0708 - val_loss: 12.7641
Epoch 87/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.8213 - loss: 0.7915 - val_accuracy: 0.0710 - val_loss: 12.8046
Epoch 88/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8252 - loss: 0.7756 - val_accuracy: 0.0728 - val_loss: 12.8663
Epoch 89/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 82s 37ms/step - accuracy: 0.8253 - loss: 0.7681 - val_accuracy: 0.0710 - val_loss: 12.9621
Epoch 90/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.8278 - loss: 0.7628 - val_accuracy: 0.0714 - val_loss: 12.9854
Epoch 91/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8308 - loss: 0.7489 - val_accuracy: 0.0714 - val_loss: 13.0877
Epoch 92/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.8306 - loss: 0.7459 - val_accuracy: 0.0708 - val_loss: 13.1058
Epoch 93/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8349 - loss: 0.7317 - val_accuracy: 0.0714 - val_loss: 13.1772
Epoch 94/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.8363 - loss: 0.7220 - val_accuracy: 0.0715 - val_loss: 13.2180
Epoch 95/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8375 - loss: 0.7153 - val_accuracy: 0.0713 - val_loss: 13.2730
Epoch 96/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.8401 - loss: 0.7078 - val_accuracy: 0.0704 - val_loss: 13.3257
Epoch 97/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8405 - loss: 0.7021 - val_accuracy: 0.0717 - val_loss: 13.3852
Epoch 98/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 36ms/step - accuracy: 0.8411 - loss: 0.6975 - val_accuracy: 0.0692 - val_loss: 13.4356
Epoch 99/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8436 - loss: 0.6873 - val_accuracy: 0.0685 - val_loss: 13.5100
Epoch 100/100
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 44s 37ms/step - accuracy: 0.8469 - loss: 0.6759 - val_accuracy: 0.0700 - val_loss: 13.5955

In [ ]:
lstm_model.save('LSTM_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
#from tensorflow.keras.models import load_model

#lstm_model = load_model("LSTM_model.h5")

In [ ]:
index_to_word={}
for word, index in word_index.items():
  index_to_word[index]=word

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text=text.lower()
  text=text.translate(translator)
  seq=tokenizer.texts_to_sequences([text])[0]
  seq=pad_sequences([seq],maxlen=max_len,padding='pre')
  pred=model.predict(seq,verbose=0)
  pred_word_index=np.argmax(pred)
  pred_word=index_to_word[pred_word_index]
  return pred_word

In [ ]:
text='school is'
next_word=predictor(lstm_model,tok,text,max_len)
print(next_word)

great

In [ ]:
def generate_text(model,tokenizer,text,max_len,n_words):
  for _ in range(n_words):
    nex_word=predictor(model,tokenizer,text,max_len)
    if next_word == "":
      break
    text+=' '+nex_word
  return text

In [ ]:
txt="The meaning of life"

res=generate_text(lstm_model,tok,txt,max_len,10)
print(res)

The meaning of life is music with the risk it the joy of a

In [ ]:
txt="are you a"

res=generate_text(lstm_model,tok,txt,max_len,10)
print(res)

are you a human being a way a dream to power power the

In [ ]:
import pickle

with open("tokenizer.pkl","wb") as f:
  pickle.dump(tok,f)

In [ ]:
with open("max_len.pkl","wb") as f:
  pickle.dump(max_len,f)